esphome:
  name: esphome-web-fe1144
  friendly_name: waveshare 143 c6
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  variant: esp32c6
  framework:
    type: esp-idf

logger:

api:

ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

pca9554:
  - id: pca9554a_device
    address: 0x20

i2c:
  - id: bus_a
    sda: 18
    scl: 8
    scan: true

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO22
    i2s_bclk_pin: GPIO21
    i2s_mclk_pin: GPIO19

audio_dac:
  - platform: es8311
    id: es8311_dac
    bits_per_sample: 16bit
    sample_rate: 48000

audio_adc:
  - platform: es7210
    id: es7210_adc
    bits_per_sample: 16bit
    sample_rate: 16000

microphone:
  - platform: i2s_audio
    id: box_mic
    i2s_audio_id: i2s_audio_bus
    i2s_din_pin: GPIO20
    adc_type: external
    channel: left
    pdm: false
    sample_rate: 16000
    bits_per_sample: 16bit

speaker:
  - platform: i2s_audio
    id: box_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO23
    dac_type: external
    audio_dac: es8311_dac
    sample_rate: 48000
    channel: mono

switch:
  - platform: gpio
    name: Speaker Enable
    icon: "mdi:speaker"
    entity_category: config
    pin:
      pca9554: pca9554a_device
      number: 7
    restore_mode: RESTORE_DEFAULT_ON

media_player:
  - platform: speaker
    name: Waveshare Speaker
    id: external_media_player

    # Critical for low-RAM boards:
    buffer_size: 20000
    codec_support_enabled: false

    announcement_pipeline:
      speaker: box_speaker
      format: WAV
      sample_rate: 16000
      num_channels: 1

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Berlin"

font:
  - file: "gfonts://Roboto"
    id: my_font
    size: 28
  - file: "gfonts://Roboto"
    id: roboto_52
    size: 52

touchscreen:
  - platform: ft63x6
    id: ts
    i2c_id: bus_a
    display: main_display
    # polling mode (required because TP_INT is on PCA9554)
    update_interval: 16ms   # ~60 Hz, smooth enough for LVGL
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: true
    on_touch:
      - lambda: |-
          ESP_LOGI("touch", "x=%d y=%d", touch.x, touch.y);

spi:
  id: display_qspi
  type: quad
  clk_pin: 11
  data_pins: [4, 5, 6, 7]

display:
  - platform: mipi_spi
    id: main_display
    model: CO5300
    bus_mode: quad
    reset_pin: GPIO3
    cs_pin: GPIO10
    dimensions:
      height: 466
      width: 466
      offset_width: 0
      offset_height: 0
    rotation: 90
lvgl:
  touchscreens:
    - ts

